WaiterApplication/Controllers/MenuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Runtime.CompilerServices;
using WaiterApplication.Attributes;
using WaiterApplication.Core.Contracts;
using WaiterApplication.Core.Models;
using WaiterApplication.Core.Models.QueryModels;
using WaiterApplication.Core.Models.ViewModel;
using WaiterApplication.Core.Models.ViewModels;
using WaiterApplication.Core.Services;
using WaiterApplication.Extensions;
using static WaiterApplication.Infrastructure.Constants.DataConstants;

namespace WaiterApplication.Controllers
{
    public class MenuController : BaseAdminController
    {
        private readonly IMenuService menuService;
        public MenuController(IMenuService _menuService)
        {
            menuService = _menuService;
        }

        [HttpGet]
        [DishNotInTheMenu]
        public async Task<IActionResult> AddDishToMenu()
        {
            if (await menuService.DishExistsAsync(User.Id()))
            {
                return RedirectToAction("Index",nameof(HomeController));
            }

            var model = new DishFormModel();

            return View(model);
        }

        [HttpPost]
        [DishNotInTheMenu]
        public async Task<IActionResult> AddDishToMenu(DishFormModel model)
        {
            if (await menuService.DishExistsAsync(User.Id()))
            {
                return RedirectToAction("Index",nameof(HomeController));
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await menuService.AddDishAsync(model.Name,
                model.Description,
                model.Image,
                model.Price,
                model.Ingredients);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> All([FromQuery] AllDishesQueryModel model)
        {
            var dishes = await menuService.AllAsync(
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.DishesPerPage);

            model.TotalDishesCount = dishes.TotalDishesCount;
            model.Dishes = dishes.Dishes;

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (await menuService.DishExistsAsync(id.ToString()) == false)
            {
                return BadRequest();
            }

            var model = await menuService.DishDetailsByIdAsync(id);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (await menuService.DishExistsAsync(id.ToString()) == false)
            {
                return BadRequest();
            }

            var dish = await menuService.DishDetailsByIdAsync(id);
            var model = new DishFormModel()
            {
                Name = dish.Name,
                Description = dish.Description,
                Image = dish.Image,
                Price = dish.Price,
                Ingredients = dish.Ingredients
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id,DishFormModel model)
        {
            if (await menuService.DishExistsAsync(id.ToString()) == false)
            {
                return BadRequest();
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await menuService.EditAsync(id, model);

            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (await menuService.DishExistsAsync(id.ToString()) == false)
            {
                return BadRequest();
            }

            var dish = await menuService.DishDetailsByIdAsync(id);
            var model = new DishRemoveViewModel()
            {
                Id = dish.Id,
                Name = dish.Name,
                Image = dish.Image,
                Price = dish.Price
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(DishRemoveViewModel model)
        {
            if (await menuService.DishExistsAsync(model.Id.ToString()) == false)
            {
                return BadRequest();
            }

            await menuService.DeleteAsync(model.Id);

            return RedirectToAction(nameof(All));
        }
    }
}

WaiterApplication/Controllers/OrderController.cs
using Humanizer.Localisation.DateToOrdinalWords;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.Logging;
using NuGet.Protocol.Core.Types;
using NuGet.Versioning;
using System.Collections.Immutable;
using System.Collections.Specialized;
using System.Runtime.InteropServices;
using WaiterApplication.Core.Contracts;
using WaiterApplication.Core.Enumerations;
using WaiterApplication.Core.Models.QueryModels;
using WaiterApplication.Core.Models.ViewModels;
using WaiterApplication.Core.Services;
using WaiterApplication.Infrastructure.Data.Models;

namespace WaiterApplication.Controllers
{
    public class OrderController : BaseController
    {
        private readonly IOrderService orderService;
        private readonly ITableService tableService;
        private readonly IMenuService menuService;
        private readonly IPromotionService promotionService;
        public OrderController(IOrderService _orderService,
            ITableService _tableService,
            IMenuService _menuService,
            IPromotionService _promotionService)
        {
            orderService = _orderService;
            tableService = _tableService;
            menuService = _menuService;
            promotionService = _promotionService;
        }
        [HttpGet]
        public async Task<IActionResult> All(List<AllOrdersViewModel> model)
        {
            model = await orderService.AllOrdersAsync();

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> GetTables()
        {
            var model = await tableService.AllAsync();

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> CreateOrder([FromQuery]int tableId)
        {
            if (await tableService.TableExistsAsync(tableId.ToString()) == false)
            {
                return BadRequest();
            }

            var table = await tableService.TableDetailsByIdAsync(tableId);

            if (table.Status == true)
            {
                return RedirectToAction(nameof(All));
            }
            else
            {
                table.Status = true;
            }

            var tableModel = await orderService.GetTableAsync(tableId);
            tableModel.Status = table.Status;

            OrderViewModel order = new OrderViewModel()
            {
                TableId = tableId,
                OrderDishes = new List<OrderDish>()
            };

            var model = new Order()
            {
                TableNumber = tableId,
                OrderedDishes = order.OrderDishes,
                CreatedOn = DateTime.Now
            };
            await orderService.CreateOrderAsync(model);
            order.OrderId = model.Id;

            return View(order);
        }
        [HttpGet]
        public async Task<IActionResult> AllDishesMenu(int orderId)
        {
            var dishes = await orderService.AllDishes(orderId);
            var promotions = await promotionService.AllPromotions();

            var combo = new OrdersAndPromotionsServiceModel()
            {
                Dishes = dishes,
                Promotions = promotions
            };

            return View(combo);
        }
        [HttpPost]
        public async Task<IActionResult> AddDish(int dishId,int orderId, string? comment)
        {
            var orderDish = new OrderDish()
            {
                DishId = dishId,
                Dish = await orderService.GetDishDetailsByIdAsync(dishId),
                OrderId = orderId,
                Quantity = 1,
                Comment = comment
            };

            await orderService.AddOrderDishToOrder(orderDish, orderId);

            return RedirectToAction(nameof(All));
        }
        [HttpGet]
        public async Task<IActionResult> Details(int orderId)
        {
            var model = await orderService.GetOrderDetailsByIdAsync(orderId);

            var dishes = new List<Dish>();

            foreach (var dishId in model.OrderDishes.Select(x => x.DishId))
            {
                var dishDetails = await orderService.GetDishDetailsByIdAsync(dishId);
                dishes.Add(dishDetails);
            }

            foreach (var item in model.OrderDishes)
            {
                var dish = dishes.FirstOrDefault(d => d.Id == item.DishId);
                item.Dish = dish;
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> AddAnotherDish(int orderId)
        {
            var dishes = await orderService.AllDishes(orderId);

            return View(dishes);
        }
        [HttpPost]
        public async Task<IActionResult> AddAnotherDish(int dishId, int orderId, string? comment)
        {
            var orderDish = new OrderDish()
            {
                DishId = dishId,
                Dish = await orderService.GetDishDetailsByIdAsync(dishId),
                OrderId = orderId,
                Quantity = 1,
                Comment = comment
            };

            await orderService.AddOrderDishToOrder(orderDish, orderId);

            return RedirectToAction(nameof(All));
        }
        [HttpPost]
        public async Task<IActionResult> RemoveOrder(int tableId,int orderId)
        {
            var order = await orderService.GetOrderDetailsByIdAsync(orderId);
            List<int> dishIds = order.OrderDishes.Select(x => x.Id).ToList();

            await orderService.RemoveOrderDishAndOrder(tableId,orderId, dishIds);
            return RedirectToAction(nameof(All));
        }
        [HttpPost]
        public async Task<IActionResult> RemoveDishFromOrder(int orderId, int dishId)
        {
            var order = await orderService.GetOrderDetailsByIdAsync(orderId);
            await orderService.RemoveOrderDishFromOrder(dishId);

            return RedirectToAction(nameof(Details), new {orderId = orderId});
        }
    }
}

WaiterApplication/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using WaiterApplication.Core.Contracts;
using WaiterApplication.Core.Models.ViewModels;
using WaiterApplication.Core.Services;

namespace WaiterApplication.Controllers
{
    public class ReportController : BaseController
    {
        private readonly IOrderService orderService;
        private readonly IReportService reportService;

        public ReportController(IOrderService _orderService,
            IReportService _reportService)
        {
            orderService = _orderService;
            reportService = _reportService;
        }

        [HttpGet]
        public async Task<IActionResult> GetReport()
        {
            var totalAmount = await reportService.TotalAmountEarned();

            var topDishes = await reportService.GetTopDishes();

            var topTables = await reportService.GetTopTables();

            ReportViewModel model = new ReportViewModel()
            {
                TotalAmountEarned = totalAmount,
                TopDishesWithNames = topDishes,
                TopTables = topTables
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> DailyReport()
        {
            var totalAmount = await reportService.DailyAmountEarned();

            var topDishes = await reportService.GetDailyTopDishes();

            var topTables = await reportService.GetDailyTopTables();

            ReportViewModel model = new ReportViewModel()
            {
                TotalAmountEarned = totalAmount,
                TopDishesWithNames = topDishes,
                TopTables = topTables
            };

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> WeeklyReport()
        {
            var totalAmount = await reportService.WeeklyAmountEarned();

            var topDishes = await reportService.GetWeeklyTopDishes();

            var topTables = await reportService.GetWeeklyTopTables();

            ReportViewModel model = new ReportViewModel()
            {
                TotalAmountEarned = totalAmount,
                TopDishesWithNames = topDishes,
                TopTables = topTables
            };

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> MonthlyReport()
        {
            var totalAmount = await reportService.MonthlyAmountEarned();

            var topDishes = await reportService.GetMonthlyTopDishes();

            var topTables = await reportService.GetMonthlyTopTables();

            ReportViewModel model = new ReportViewModel()
            {
                TotalAmountEarned = totalAmount,
                TopDishesWithNames = topDishes,
                TopTables = topTables
            };

            return View(model);
        }
    }
}

WaiterApplication/Controllers/TableController.cs
using Microsoft.AspNetCore.Mvc;
using WaiterApplication.Core.Contracts;
using WaiterApplication.Core.Models.ViewModels;
using WaiterApplication.Extensions;

namespace WaiterApplication.Controllers
{
    public class TableController : BaseAdminController
    {
        private readonly ITableService tableService;
        public TableController(ITableService _tableService)
        {
            tableService = _tableService;
        }
        [HttpGet]
        public async Task<IActionResult> All()
        {
            var tables = await tableService.AllAsync();

            return View(tables);
        }
        [HttpGet]
        public async Task<IActionResult> CreateTable()
        {
            if (await tableService.TableExistsAsync(User.Id()))
            {
                return RedirectToAction("All");
            }

            var model = new TableViewModel();

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> CreateTable(TableViewModel model)
        {
            if (await tableService.TableExistsAsync(User.Id()))
            {
                return RedirectToAction("All");
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await tableService.CreateTableAsync(model.Name,
                model.Capacity,
                model.Status);

            return RedirectToAction("All");
        }
        [HttpGet]
        public async Task<IActionResult> RemoveTable(int tableId)
        {
            if (await tableService.TableExistsAsync(tableId.ToString()) == false)
            {
                return BadRequest();
            }

            var table = await tableService.TableDetailsByIdAsync(tableId);

            TableViewModel model = new TableViewModel()
            {
                Id = table.Id,
                Name = table.Name,
                Capacity = table.Capacity
            };

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> RemoveTable(TableViewModel model)
        {
            if (!await tableService.TableExistsAsync(model.Id.ToString()))
            {
                return BadRequest();
            }
            await tableService.RemoveTable(model.Id);

            return RedirectToAction("All");
        }
        [HttpGet]
        public async Task<IActionResult> TableDetails(int tableId)
        {
            var table = await tableService.TableDetailsByIdAsync(tableId);

            return View(table);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int tableId)
        {
            if (await tableService.TableExistsAsync(tableId.ToString()) == false)
            {
                return BadRequest();
            }
            var tableToEdit = await tableService.TableDetailsByIdAsync(tableId);
            var model = new TableViewModel()
            {
                Id = tableToEdit.Id,
                Name = tableToEdit.Name,
                Capacity = tableToEdit.Capacity,
                Status = tableToEdit.Status
            };

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(TableViewModel model)
        {
            if (await tableService.TableExistsAsync(model.Id.ToString()) == false)
            {
                return BadRequest();
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await tableService.EditAsync(model);

            return RedirectToAction("All");
        }
    }
}

WaiterApplication/Views/Shared/_DishPartial.cshtml
@using WaiterApplication.Core.Models.QueryModels﻿;
@model AllDishesServiceModel

<hr />

<div class="row justify-content-center">
    <div class="col-md-4 mx-auto"> 
        <div class="card mb-3">
             @if (!string.IsNullOrEmpty(@Model.Image))
            {
                <img class="card-img-top" src="@Model.Image" alt="Dish Image">
            }
            <div class="card-body text-center">
                <h4>@Model.Name</h4>
                <p>@Model.Description</p>
                <h6>Price: <b>@String.Format("{0:f2}", @Model.Price)</b></h6>
                @if (!string.IsNullOrEmpty(@Model.Ingredients))
                {
                    <h6>Ingredients:</h6>
                    <p>@Model.Ingredients</p>
                }
                <br />
                <a asp-controller="Menu" asp-action="Details" asp-route-id="@Model.Id"
                   class="btn btn-success">Details</a>
            </div>
        </div>
    </div>
</div>

WaiterApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WaiterApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WaiterApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WaiterApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1">
        @if (User.Identity.IsAuthenticated)
        {
        <ul class="navbar-nav flex-grow-1">
          <li class="nav-item">
               <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
          </li>
          <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="All">All Dishes</a>
          </li>
          <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Table" asp-action="All">All Tables</a>
          </li>
          <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="GetTables">Create Order</a>
          </li>
          <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Promotion" asp-action="AllDishes">Promos</a>
          </li>
          <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Promotion" asp-action="AllPromotions">All Promos</a>
          </li>
        </ul>
        }
        @if (User.IsInRole("Administrator"))
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="GetReport">Get Report</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="AddDishToMenu">Add Dish to Menu</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Table" asp-action="CreateTable">Create Table</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="All">All Orders</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="All">All Items</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="CreateItem">Create Item</a>
            </li>
        }
    </ul>
    <partial name="_LoginPartial" />
</div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WaiterApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>